// Generated by `npm run contracts:generate` from the app's registry and its FRONTEND.
import type { FrontendFeature } from '../../core/shell/frontend/runtime/slots.js';
import { feature as home } from '../../features/home/frontend/feature.js';
import { feature as timecard } from '../../features/timecard/frontend/feature.js';
import { feature as uniforms } from '../../features/uniforms/frontend/feature.js';
import { feature as dvic } from '../../features/dvic/frontend/feature.js';
import { feature as team } from '../../features/team/frontend/feature.js';
import { feature as settings } from '../../features/settings/frontend/feature.js';
import { feature as driverMatch } from '../../features/driver_match/frontend/feature.js';
import { feature as routes } from '../../features/routes/frontend/feature.js';
import { feature as scorecard } from '../../features/scorecard/frontend/feature.js';
import { feature as paycom } from '../../collectors/paycom/frontend/feature.js';
import { feature as cortex } from '../../collectors/cortex/frontend/feature.js';
import { feature as accounts } from '../../core/accounts/frontend/feature.js';
import { feature as collection } from '../../core/collection/frontend/feature.js';
import { feature as platformOwner } from '../../core/platform_owner/frontend/feature.js';

// Every owner's frontend manifest: the features, the collectors, then core's parts with screens.
// The order is the sidebar's, and the order in which Settings tabs warm their reads.
export const features: readonly FrontendFeature[] = [
  home,
  timecard,
  uniforms,
  dvic,
  team,
  settings,
  driverMatch,
  routes,
  scorecard,
  paycom,
  cortex,
  accounts,
  collection,
  platformOwner,
];
