//! Safe projections of verified upstream daily fields; raw locations and videos stay out of agent answers.
pub const QUALITY: &[&str] = &[
    "delivered",
    "dispatched",
    "completed_routes",
    "delivery_attempt",
    "delivery_attempt_percent",
    "delivery_success",
    "first_day_delivery_success_percent",
    "dnr",
    "dnr_dpmo",
    "pde_photos_taken",
    "pod_bypass",
    "pod_inappropriate_photos",
    "pod_opportunity",
    "pod_success",
    "pod_success_rate",
    "rts_dpmo",
    "transferred_out",
];
pub const RETURNS: &[&str] = &[
    "tracking_id",
    "delivery_planned_date",
    "rts_reason_code",
    "impacting_dcr",
    "daily_coaching",
    "daily_exemption",
    "daily_exemption_reason",
];
pub const RETURN_COUNTS: &[&str] = &[
    "rts_all",
    "rts_all_controllable",
    "rts_all_exempted",
    "rts_business_closed",
    "rts_customer_unavailable",
    "rts_damaged",
    "rts_bad_weather",
    "rts_no_secure_location",
    "rts_inaccessible_delivery_location",
    "rts_address_not_found",
];
pub const FEEDBACK: &[&str] = &[
    "positive_response_cnt",
    "negative_response_cnt",
    "above_and_beyond_cnt",
    "care_for_others_cnt",
    "delivered_to_wrong_address_cnt",
    "delivered_with_care_cnt",
    "driver_mishandled_package_cnt",
    "driver_was_driving_unsafely_cnt",
    "driver_was_unprofessional_cnt",
    "followed_instructions_cnt",
    "friendly_cnt",
    "item_damaged_cnt",
    "late_delivery_cnt",
    "never_received_delivery_cnt",
    "not_delivered_to_preferred_location_cnt",
    "on_time_cnt",
    "received_wrong_item_cnt",
    "respectful_of_property_cnt",
    "tmd_cnt",
    "was_great_cnt",
    "was_not_so_great_cnt",
];
pub const BEHAVIORS: &[&str] = &[
    "dsb_count",
    "dsb_dpmo",
    "dac_dnr_count",
    "dac_loss_count",
    "dnr_count",
    "no_pod_bucket_count",
    "simultaneous_del_bucket_count",
    "del_greater_50m_dist_count",
    "total_deliveries",
    "attended_count",
    "unattended_count",
];
pub const PICKUPS: &[&str] = &[
    "successful_stops",
    "failed_stops",
    "total_stops",
    "early_arrivals",
    "late_arrivals",
    "greater_than_500m",
    "not_attempted_pickups",
    "psb_metric",
    "psb_score",
    "psb_tier",
];
pub const SAFETY: &[&str] = &[
    "distraction_rate",
    "distraction_events",
    "distraction_events_weighted",
    "distractions_denominator",
    "following_distance_rate",
    "following_distance_events",
    "following_distance_denominator",
    "seatbelt_rate",
    "seatbelt_events",
    "seatbelt_denominator",
    "sign_signal_rate",
    "sign_signal_events",
    "sign_signal_denominator",
    "speeding_rate",
    "speeding_events",
    "speeding_denominator",
    "dsp_oss_metric",
    "dsp_oss_score",
    "dsp_oss_tier",
];
pub const EVENTS: &[&str] = &[
    "event_id",
    "type",
    "subtype",
    "dashboard_metric_type",
    "severity",
    "data_date",
    "event_start_time_local",
    "event_end_time_local",
    "event_duration",
    "vehicle_speed",
    "speed_limit",
    "oss_impact_flag",
    "oss_impact",
    "oss_eligible_flag",
    "factored_into_initial_scorecard",
    "final_resolution",
    "event_receive_time_utc",
    "event_time_zone",
];
pub const DEVICES: &[&str] = &[
    "trip_count",
    "working_device_count",
    "bad_mount_count",
    "camera_obstructed_count",
    "device_not_installed_count",
    "device_unresponsive_count",
    "trips_with_defects_not_exempted",
    "trips_with_exemptions",
];
pub const THRESHOLDS: &[&str] = &[
    "metric",
    "metric_name",
    "indicator",
    "n0",
    "n1",
    "n2",
    "n3",
    "n4",
    "t0",
    "t1",
    "t2",
    "t3",
    "t4",
    "version",
    "start_date",
    "end_date",
    "program",
    "country",
    "region",
];
pub fn of(dataset: &str) -> &'static [&'static str] {
    match dataset {
        "driver_quality" | "dsp_quality" => QUALITY,
        "returns_to_station" => RETURNS,
        "driver_returns" | "dsp_returns" => RETURN_COUNTS,
        "driver_feedback" | "dsp_feedback" => FEEDBACK,
        "driver_delivery_behaviors" | "dsp_delivery_behaviors" => BEHAVIORS,
        "driver_pickups" | "dsp_pickups" => PICKUPS,
        "driver_safety" | "dsp_safety" | "driver_safety_batch" | "dsp_safety_batch" => SAFETY,
        "safety_events" | "live_safety_events" => EVENTS,
        "working_devices" => DEVICES,
        "driver_thresholds" | "dsp_thresholds" => THRESHOLDS,
        // Contacts were empty during inspection; their field contract is not invented.
        _ => &[],
    }
}

/// Shared category words resolve to verified daily count fields, never individual reviews.
pub const FEEDBACK_TYPES: &[(&str, &str)] = &[
    ("wrong_address", "delivered_to_wrong_address_cnt"),
    ("never_received", "never_received_delivery_cnt"),
    ("mishandled", "driver_mishandled_package_cnt"),
    ("unsafe_driving", "driver_was_driving_unsafely_cnt"),
    ("unprofessional", "driver_was_unprofessional_cnt"),
    (
        "not_preferred_location",
        "not_delivered_to_preferred_location_cnt",
    ),
    ("wrong_item", "received_wrong_item_cnt"),
    ("above_and_beyond", "above_and_beyond_cnt"),
    ("delivered_with_care", "delivered_with_care_cnt"),
    ("friendly", "friendly_cnt"),
    ("followed_instructions", "followed_instructions_cnt"),
    ("respectful_of_property", "respectful_of_property_cnt"),
    ("thank_my_driver", "tmd_cnt"),
    ("care_for_others", "care_for_others_cnt"),
    ("item_damaged", "item_damaged_cnt"),
    ("late_delivery", "late_delivery_cnt"),
    ("on_time", "on_time_cnt"),
    ("was_great", "was_great_cnt"),
    ("was_not_so_great", "was_not_so_great_cnt"),
];
