CREATE TABLE account_passkeys ( id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, credential TEXT NOT NULL, name TEXT NOT NULL, created_at INTEGER NOT NULL );
CREATE TABLE authenticator_apps ( user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, secret TEXT NOT NULL, created_at INTEGER NOT NULL, last_counter INTEGER NOT NULL DEFAULT -1 );
CREATE TABLE "collection_schedules" ( id TEXT PRIMARY KEY, name TEXT NOT NULL, collection TEXT NOT NULL, cadence TEXT NOT NULL CHECK(cadence IN ('interval','daily')), interval_minutes INTEGER, local_time TEXT NOT NULL, anchor INTEGER NOT NULL, enabled INTEGER NOT NULL CHECK(enabled IN (0,1)), next_run TEXT, revision INTEGER NOT NULL DEFAULT 1, last_error TEXT, created_at TEXT NOT NULL );
CREATE TABLE documents_connect_requests ( state_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL, verifier TEXT NOT NULL, expires_at INTEGER NOT NULL );
CREATE TABLE documents_connection ( id INTEGER PRIMARY KEY CHECK (id = 1), status TEXT NOT NULL CHECK (status IN ('connected', 'broken')), account_email TEXT NOT NULL, account_kind TEXT NOT NULL CHECK (account_kind IN ('workspace', 'personal')), folder_id TEXT NOT NULL, folder_name TEXT NOT NULL, connected_by TEXT NOT NULL, connected_at TEXT NOT NULL, broken_at TEXT );
CREATE TABLE documents_files ( file_id TEXT PRIMARY KEY, added_by TEXT NOT NULL, added_at TEXT NOT NULL, changed_by TEXT NOT NULL, changed_at TEXT NOT NULL );
CREATE TABLE documents_people ( user_id TEXT PRIMARY KEY, linked_email TEXT, shared_email TEXT, share_id TEXT, state TEXT NOT NULL CHECK (state IN ('shared', 'needs_account', 'refused')), refusal TEXT, emailed_at TEXT, updated_at TEXT NOT NULL );
CREATE TABLE invitations ( hash TEXT PRIMARY KEY, dsp_id TEXT NOT NULL, email TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('owner','manager','member')), expires_at INTEGER NOT NULL, created_by TEXT NOT NULL, used_at INTEGER, role_id TEXT );
CREATE TABLE memberships ( id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), dsp_id TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('owner','manager','member')), role_id TEXT REFERENCES roles(id), UNIQUE(user_id,dsp_id) );
CREATE TABLE owner_migrations (owner TEXT NOT NULL, id INTEGER NOT NULL, name TEXT NOT NULL, applied_at INTEGER NOT NULL, PRIMARY KEY(owner, id));
CREATE TABLE people ( code TEXT PRIMARY KEY, created_at TEXT NOT NULL, merged_into TEXT REFERENCES people(code), merged_at TEXT, merged_by TEXT, split_from TEXT REFERENCES people(code), created_by TEXT );
CREATE TABLE people_apart ( first TEXT NOT NULL REFERENCES people(code), second TEXT NOT NULL REFERENCES people(code), decided_at TEXT NOT NULL, actor_id TEXT, PRIMARY KEY(first, second), CHECK(first < second) );
CREATE TABLE person_ids ( source TEXT NOT NULL CHECK(source IN ('paycom','amazon')), external_id TEXT NOT NULL, code TEXT NOT NULL REFERENCES people(code), linked_by TEXT NOT NULL CHECK(linked_by IN ('new','name','variant','saved','person')), linked_at TEXT NOT NULL, actor_id TEXT, PRIMARY KEY(source, external_id) );
CREATE TABLE recovery_codes ( hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE );
CREATE TABLE resets ( hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), user_version INTEGER NOT NULL, expires_at INTEGER NOT NULL, used_at INTEGER );
CREATE TABLE roles ( id TEXT PRIMARY KEY, dsp_id TEXT NOT NULL, name TEXT NOT NULL COLLATE NOCASE, permissions TEXT NOT NULL DEFAULT '[]', system INTEGER NOT NULL DEFAULT 0 CHECK(system IN (0,1)), created_at TEXT NOT NULL, UNIQUE(dsp_id,name) );
CREATE TABLE schema_migrations (id INTEGER PRIMARY KEY, name TEXT NOT NULL, applied_at INTEGER NOT NULL);
CREATE TABLE security_challenges ( session_hash TEXT PRIMARY KEY REFERENCES sessions(hash) ON DELETE CASCADE, kind TEXT NOT NULL, state TEXT NOT NULL, expires_at INTEGER NOT NULL );
CREATE TABLE session_metadata ( session_hash TEXT PRIMARY KEY REFERENCES sessions(hash) ON DELETE CASCADE, device TEXT NOT NULL );
CREATE TABLE session_security ( session_hash TEXT PRIMARY KEY REFERENCES sessions(hash) ON DELETE CASCADE, verified_at INTEGER NOT NULL DEFAULT 0, password_verified_at INTEGER NOT NULL DEFAULT 0 );
CREATE TABLE sessions ( hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), user_version INTEGER NOT NULL, expires_at INTEGER NOT NULL, created_at INTEGER NOT NULL );
CREATE TABLE settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE storage_identity ( dsp_id TEXT PRIMARY KEY, provider TEXT NOT NULL, source TEXT NOT NULL );
CREATE TABLE uniform_events ( revision INTEGER PRIMARY KEY, kind TEXT NOT NULL CHECK (kind IN ('initialized', 'created', 'updated', 'archived', 'adjusted')), uniform_id TEXT, uniform_name TEXT NOT NULL, variant_id TEXT, fit TEXT, size TEXT, delta INTEGER, quantity INTEGER, actor_id TEXT NOT NULL, actor_name TEXT NOT NULL, request_id TEXT UNIQUE, at TEXT NOT NULL );
CREATE TABLE uniform_inventory ( id INTEGER PRIMARY KEY CHECK (id = 1), revision INTEGER NOT NULL DEFAULT 0 );
CREATE TABLE uniform_variants ( id TEXT PRIMARY KEY, uniform_id TEXT NOT NULL REFERENCES uniforms(id), fit TEXT NOT NULL CHECK (fit IN ('men', 'women', 'unisex')), size TEXT NOT NULL, quantity INTEGER NOT NULL DEFAULT 0 CHECK (quantity BETWEEN 0 AND 1000000), revision INTEGER NOT NULL, position INTEGER NOT NULL, archived INTEGER NOT NULL DEFAULT 0 CHECK (archived IN (0, 1)) );
CREATE TABLE uniforms ( id TEXT PRIMARY KEY, name TEXT NOT NULL, category TEXT NOT NULL, revision INTEGER NOT NULL, position INTEGER NOT NULL, archived INTEGER NOT NULL DEFAULT 0 CHECK (archived IN (0, 1)) );
CREATE TABLE users ( id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE COLLATE NOCASE, first_name TEXT NOT NULL, last_name TEXT NOT NULL, password TEXT NOT NULL, platform_owner INTEGER NOT NULL DEFAULT 0 CHECK(platform_owner=0), status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','disabled')), version INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL );
CREATE INDEX account_passkeys_user ON account_passkeys(user_id);
CREATE INDEX invitations_dsp_owner ON invitations(dsp_id,role,expires_at DESC) WHERE used_at IS NULL;
CREATE INDEX invitations_expiry ON invitations(expires_at);
CREATE INDEX invitations_role ON invitations(role_id) WHERE used_at IS NULL;
CREATE INDEX memberships_dsp_role ON memberships(dsp_id,role,user_id);
CREATE INDEX memberships_role ON memberships(role_id);
CREATE INDEX person_ids_code ON person_ids(code);
CREATE INDEX recovery_codes_user ON recovery_codes(user_id);
CREATE INDEX resets_expiry ON resets(expires_at);
CREATE UNIQUE INDEX roles_owner ON roles(dsp_id) WHERE system=1;
CREATE INDEX session_expiry ON sessions(expires_at);
CREATE UNIQUE INDEX uniform_variants_size ON uniform_variants (uniform_id, fit, size COLLATE NOCASE) WHERE archived = 0;
CREATE INDEX uniform_variants_uniform ON uniform_variants (uniform_id, archived, position);
CREATE UNIQUE INDEX uniforms_name ON uniforms (name COLLATE NOCASE) WHERE archived = 0;
