CREATE TABLE collection_checkpoint_pages (job_id TEXT NOT NULL REFERENCES collection_checkpoints(job_id) ON DELETE CASCADE, employee_code TEXT NOT NULL, data TEXT NOT NULL, PRIMARY KEY(job_id,employee_code));
CREATE TABLE collection_checkpoints (job_id TEXT PRIMARY KEY, connection_revision INTEGER NOT NULL, fingerprint TEXT NOT NULL, created_at INTEGER NOT NULL, token TEXT NOT NULL UNIQUE);
CREATE TABLE collection_live_items (job_id TEXT NOT NULL REFERENCES collection_live_runs(job_id) ON DELETE CASCADE, item_key TEXT NOT NULL, date TEXT NOT NULL, data TEXT NOT NULL, PRIMARY KEY(job_id,date,item_key));
CREATE TABLE collection_live_runs (job_id TEXT PRIMARY KEY, owner TEXT NOT NULL, metadata TEXT NOT NULL);
CREATE TABLE connections (provider TEXT PRIMARY KEY CHECK(provider='paycom'), enabled INTEGER NOT NULL DEFAULT 0 CHECK(enabled IN (0,1)), status TEXT NOT NULL DEFAULT 'not_connected', error TEXT, account_label TEXT, updated_at TEXT NOT NULL, verified_at TEXT, revision INTEGER NOT NULL DEFAULT 1);
CREATE TABLE employee_timecard_syncs ( employee_code TEXT NOT NULL, period_from TEXT NOT NULL, period_to TEXT NOT NULL, collected_at TEXT NOT NULL, data TEXT NOT NULL, PRIMARY KEY(employee_code, period_from, period_to) );
CREATE TABLE employees (publication_id TEXT NOT NULL REFERENCES publications(id) ON DELETE CASCADE, code TEXT NOT NULL, name TEXT NOT NULL, department TEXT NOT NULL, position TEXT NOT NULL, station TEXT NOT NULL, active INTEGER NOT NULL, PRIMARY KEY(publication_id,code));
CREATE TABLE publications (id TEXT PRIMARY KEY, collected_at TEXT NOT NULL, period_from TEXT NOT NULL, period_to TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 0 CHECK(active IN (0,1)));
CREATE TABLE schedules (provider TEXT PRIMARY KEY CHECK(provider='paycom'), enabled INTEGER NOT NULL DEFAULT 0 CHECK(enabled IN (0,1)), local_time TEXT NOT NULL DEFAULT '06:00', timezone TEXT NOT NULL, next_run TEXT);
CREATE TABLE schema_migrations (id INTEGER PRIMARY KEY, name TEXT NOT NULL, applied_at INTEGER NOT NULL);
CREATE TABLE settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE storage_identity (dsp_id TEXT NOT NULL, provider TEXT NOT NULL, source TEXT NOT NULL);
CREATE TABLE timecard_sources (publication_id TEXT NOT NULL, employee_code TEXT NOT NULL, period_key TEXT NOT NULL, url TEXT NOT NULL, PRIMARY KEY(publication_id,employee_code), FOREIGN KEY(publication_id,employee_code) REFERENCES employees(publication_id,code) ON DELETE CASCADE);
CREATE TABLE timecards (publication_id TEXT NOT NULL REFERENCES publications(id) ON DELETE CASCADE, employee_code TEXT NOT NULL, date TEXT NOT NULL, hours REAL NOT NULL, status TEXT NOT NULL, punches TEXT NOT NULL, PRIMARY KEY(publication_id,employee_code,date), FOREIGN KEY(publication_id,employee_code) REFERENCES employees(publication_id,code) ON DELETE CASCADE);
CREATE UNIQUE INDEX active_publication ON publications(active) WHERE active=1;
CREATE INDEX employees_by_code ON employees(code, publication_id);
CREATE INDEX publications_by_collection ON publications(collected_at DESC);
CREATE INDEX timecards_by_day ON timecards(publication_id,date,employee_code);
