CREATE TABLE account_passkeys ( id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, credential TEXT NOT NULL, name TEXT NOT NULL, created_at INTEGER NOT NULL );
CREATE TABLE agent_activity ( id INTEGER PRIMARY KEY, at INTEGER NOT NULL, key_id TEXT NOT NULL, key_name TEXT NOT NULL, key_kind TEXT NOT NULL CHECK(key_kind IN ('key','app')), surface TEXT NOT NULL, dsp_id TEXT, dsp_name TEXT, outcome TEXT NOT NULL, ms INTEGER NOT NULL, bytes INTEGER NOT NULL , bypassed INTEGER NOT NULL DEFAULT 0);
CREATE TABLE agent_key_dsp_reads ( key_id TEXT NOT NULL REFERENCES agent_keys(id) ON DELETE CASCADE, dsp_id TEXT NOT NULL REFERENCES dsps(id), areas TEXT NOT NULL, bypass INTEGER NOT NULL CHECK(bypass IN (0,1)), PRIMARY KEY(key_id, dsp_id) );
CREATE TABLE agent_key_dsps ( key_id TEXT NOT NULL REFERENCES agent_keys(id) ON DELETE CASCADE, dsp_id TEXT NOT NULL REFERENCES dsps(id), PRIMARY KEY(key_id, dsp_id) );
CREATE TABLE agent_key_tools ( key_id TEXT NOT NULL REFERENCES agent_keys(id) ON DELETE CASCADE, tool TEXT NOT NULL, allowed INTEGER NOT NULL CHECK(allowed IN (0,1)), PRIMARY KEY(key_id, tool) );
CREATE TABLE agent_keys ( id TEXT PRIMARY KEY, name TEXT NOT NULL, hash TEXT NOT NULL UNIQUE, hint TEXT NOT NULL, user_id TEXT NOT NULL REFERENCES users(id), all_dsps INTEGER NOT NULL CHECK(all_dsps IN (0,1)), access TEXT NOT NULL CHECK(access IN ('read','operator')), tools TEXT NOT NULL CHECK(tools IN ('full','essential')), locations INTEGER NOT NULL CHECK(locations IN (0,1)), created_at TEXT NOT NULL, expires_at TEXT, revoked_at TEXT, last_used_at TEXT, last_client TEXT , kind TEXT NOT NULL DEFAULT 'key' CHECK(kind IN ('key','app')), client_id TEXT, client_name TEXT, client_verified INTEGER NOT NULL DEFAULT 0, areas TEXT NOT NULL DEFAULT 'routes,timecards,meal_breaks,dvic,feedback,safety,returns,scorecard', bypass INTEGER NOT NULL DEFAULT 0 CHECK(bypass IN (0,1)), all_tools INTEGER NOT NULL DEFAULT 1 CHECK(all_tools IN (0,1)));
CREATE TABLE audit (id INTEGER PRIMARY KEY, at TEXT NOT NULL, actor_id TEXT REFERENCES users(id), dsp_id TEXT REFERENCES dsps(id), action TEXT NOT NULL, detail TEXT NOT NULL DEFAULT '', actor_name TEXT, data TEXT, shown INTEGER, member_id TEXT);
CREATE TABLE authenticator_apps ( user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, secret TEXT NOT NULL, created_at INTEGER NOT NULL, last_counter INTEGER NOT NULL DEFAULT -1 );
CREATE TABLE driver_codes ( code TEXT PRIMARY KEY, dsp_id TEXT NOT NULL, created_at TEXT NOT NULL );
CREATE TABLE dsp_features ( dsp_id TEXT NOT NULL REFERENCES dsps(id), feature TEXT NOT NULL, enabled INTEGER NOT NULL CHECK(enabled IN (0,1)), changed_by TEXT, changed_at TEXT NOT NULL, shown INTEGER NOT NULL DEFAULT 1 CHECK (shown IN (0, 1)), PRIMARY KEY(dsp_id,feature) );
CREATE TABLE dsps (id TEXT PRIMARY KEY, name TEXT NOT NULL, environment TEXT NOT NULL CHECK(environment IN ('production','preview')), status TEXT NOT NULL CHECK(status IN ('provisioning','active','suspended','failed')), timezone TEXT NOT NULL, permanent INTEGER NOT NULL DEFAULT 0 CHECK(permanent IN (0,1)), revision INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, code TEXT);
CREATE TABLE feature_availability ( feature TEXT PRIMARY KEY, mandatory INTEGER NOT NULL CHECK (mandatory IN (0, 1)) );
CREATE TABLE invitation_routes (hash TEXT PRIMARY KEY, dsp_id TEXT NOT NULL REFERENCES dsps(id));
CREATE TABLE invitations (hash TEXT PRIMARY KEY, dsp_id TEXT NOT NULL REFERENCES dsps(id), email TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('owner','manager','member')), expires_at INTEGER NOT NULL, created_by TEXT NOT NULL REFERENCES users(id), used_at INTEGER, role_id TEXT);
CREATE TABLE memberships (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), dsp_id TEXT NOT NULL REFERENCES dsps(id), role TEXT NOT NULL CHECK(role IN ('owner','manager','member')), role_id TEXT REFERENCES roles(id), UNIQUE(user_id,dsp_id));
CREATE TABLE oauth_apps ( id TEXT PRIMARY KEY, allowed INTEGER NOT NULL CHECK(allowed IN (0,1)), changed_by TEXT NOT NULL, changed_at TEXT NOT NULL );
CREATE TABLE oauth_clients ( id TEXT PRIMARY KEY, name TEXT NOT NULL, redirect_uris TEXT NOT NULL, created_at TEXT NOT NULL, last_used_at TEXT );
CREATE TABLE oauth_codes ( hash TEXT PRIMARY KEY, client_id TEXT NOT NULL, client_name TEXT NOT NULL, client_verified INTEGER NOT NULL CHECK(client_verified IN (0,1)), redirect_uri TEXT NOT NULL, code_challenge TEXT NOT NULL, resource TEXT NOT NULL, choices TEXT NOT NULL, approved_by TEXT NOT NULL, created_at TEXT NOT NULL, expires_at TEXT NOT NULL, used_at TEXT, key_id TEXT );
CREATE TABLE oauth_pairing ( id INTEGER PRIMARY KEY CHECK(id=1), open_until TEXT NOT NULL, opened_by TEXT NOT NULL, opened_at TEXT NOT NULL );
CREATE TABLE oauth_requests ( id TEXT PRIMARY KEY, client_id TEXT NOT NULL, client_name TEXT NOT NULL, verified INTEGER NOT NULL CHECK(verified IN (0,1)), redirect_uri TEXT NOT NULL, state TEXT, code_challenge TEXT NOT NULL, resource TEXT NOT NULL, scope TEXT NOT NULL, created_at TEXT NOT NULL, expires_at TEXT NOT NULL , browser TEXT);
CREATE TABLE oauth_tokens ( hash TEXT PRIMARY KEY, key_id TEXT NOT NULL REFERENCES agent_keys(id) ON DELETE CASCADE, kind TEXT NOT NULL CHECK(kind IN ('access','refresh')), resource TEXT NOT NULL, created_at TEXT NOT NULL, expires_at TEXT NOT NULL, used_at TEXT, replaced_at TEXT );
CREATE TABLE outbox (id TEXT PRIMARY KEY, encrypted_message TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', attempts INTEGER NOT NULL DEFAULT 0, available_at INTEGER NOT NULL, sent_at TEXT, created_at INTEGER, last_attempt_at INTEGER, last_error TEXT, kind TEXT, invitation_hash TEXT, user_id TEXT, dsp_id TEXT);
CREATE TABLE owner_migrations (owner TEXT NOT NULL, id INTEGER NOT NULL, name TEXT NOT NULL, applied_at INTEGER NOT NULL, PRIMARY KEY(owner, id));
CREATE TABLE passkeys ( id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, credential TEXT NOT NULL, name TEXT NOT NULL, created_at INTEGER NOT NULL );
CREATE TABLE recovery_codes ( hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE );
CREATE TABLE resets (hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), user_version INTEGER NOT NULL, expires_at INTEGER NOT NULL, used_at INTEGER);
CREATE TABLE roles (id TEXT PRIMARY KEY, dsp_id TEXT NOT NULL REFERENCES dsps(id), name TEXT NOT NULL COLLATE NOCASE, permissions TEXT NOT NULL DEFAULT '[]', system INTEGER NOT NULL DEFAULT 0 CHECK(system IN (0,1)), created_at TEXT NOT NULL, UNIQUE(dsp_id,name));
CREATE TABLE schema_migrations (id INTEGER PRIMARY KEY, name TEXT NOT NULL, applied_at INTEGER NOT NULL);
CREATE TABLE security_challenges ( session_hash TEXT PRIMARY KEY REFERENCES sessions(hash) ON DELETE CASCADE, kind TEXT NOT NULL, state TEXT NOT NULL, expires_at INTEGER NOT NULL );
CREATE TABLE session_metadata ( session_hash TEXT PRIMARY KEY REFERENCES sessions(hash) ON DELETE CASCADE, device TEXT NOT NULL );
CREATE TABLE session_security ( session_hash TEXT PRIMARY KEY REFERENCES sessions(hash) ON DELETE CASCADE, verified_at INTEGER NOT NULL DEFAULT 0, password_verified_at INTEGER NOT NULL DEFAULT 0 );
CREATE TABLE sessions (hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), user_version INTEGER NOT NULL, expires_at INTEGER NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE throttle (key TEXT PRIMARY KEY, count INTEGER NOT NULL, reset_at INTEGER NOT NULL, namespace TEXT NOT NULL DEFAULT 'legacy');
CREATE TABLE users (id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE COLLATE NOCASE, first_name TEXT NOT NULL, last_name TEXT NOT NULL, password TEXT NOT NULL, platform_owner INTEGER NOT NULL DEFAULT 0 CHECK(platform_owner IN (0,1)), status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','disabled')), version INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL);
CREATE INDEX account_passkeys_user ON account_passkeys(user_id);
CREATE INDEX agent_activity_key ON agent_activity(key_id, at);
CREATE INDEX agent_activity_refused ON agent_activity(at) WHERE outcome<>'ok';
CREATE INDEX agent_activity_time ON agent_activity(at);
CREATE INDEX audit_dsp_time ON audit(dsp_id,id DESC);
CREATE UNIQUE INDEX dsps_code ON dsps(code);
CREATE INDEX invitations_dsp_owner ON invitations(dsp_id,role,expires_at DESC) WHERE used_at IS NULL;
CREATE INDEX invitations_expiry ON invitations(expires_at);
CREATE INDEX invitations_role ON invitations(role_id) WHERE used_at IS NULL;
CREATE INDEX memberships_dsp_role ON memberships(dsp_id,role,user_id);
CREATE INDEX memberships_role ON memberships(role_id);
CREATE INDEX oauth_tokens_expiry ON oauth_tokens(expires_at);
CREATE INDEX oauth_tokens_key ON oauth_tokens(key_id);
CREATE INDEX outbox_last_attempt ON outbox(last_attempt_at DESC);
CREATE INDEX outbox_pending ON outbox(status,available_at);
CREATE INDEX outbox_sent ON outbox(sent_at DESC);
CREATE INDEX passkeys_user ON passkeys(user_id);
CREATE UNIQUE INDEX permanent_dev ON dsps(permanent) WHERE permanent=1;
CREATE INDEX recovery_codes_user ON recovery_codes(user_id);
CREATE INDEX resets_expiry ON resets(expires_at);
CREATE UNIQUE INDEX roles_owner ON roles(dsp_id) WHERE system=1;
CREATE INDEX session_expiry ON sessions(expires_at);
CREATE INDEX throttle_expiry ON throttle(reset_at);
CREATE INDEX throttle_namespace_expiry ON throttle(namespace, reset_at);
