CREATE TABLE customer_feedback ( publication_id TEXT NOT NULL REFERENCES weekly_scorecard_publications(id) ON DELETE CASCADE, row_index INTEGER NOT NULL, week TEXT, data_date TEXT, transporter_id TEXT, tracking_id TEXT, event_id TEXT, impact INTEGER, row TEXT NOT NULL CHECK(json_valid(row)), PRIMARY KEY(publication_id,row_index) );
CREATE TABLE delivery_concessions ( publication_id TEXT NOT NULL REFERENCES weekly_scorecard_publications(id) ON DELETE CASCADE, row_index INTEGER NOT NULL, week TEXT, data_date TEXT, transporter_id TEXT, tracking_id TEXT, event_id TEXT, impact INTEGER, row TEXT NOT NULL CHECK(json_valid(row)), PRIMARY KEY(publication_id,row_index) );
CREATE TABLE driver_safety ( publication_id TEXT NOT NULL REFERENCES weekly_scorecard_publications(id) ON DELETE CASCADE, row_index INTEGER NOT NULL, week TEXT, data_date TEXT, transporter_id TEXT, tracking_id TEXT, event_id TEXT, impact INTEGER, row TEXT NOT NULL CHECK(json_valid(row)), PRIMARY KEY(publication_id,row_index) );
CREATE TABLE driver_weekly_scorecards ( publication_id TEXT NOT NULL REFERENCES weekly_scorecard_publications(id) ON DELETE CASCADE, row_index INTEGER NOT NULL, week TEXT, data_date TEXT, transporter_id TEXT, tracking_id TEXT, event_id TEXT, impact INTEGER, row TEXT NOT NULL CHECK(json_valid(row)), PRIMARY KEY(publication_id,row_index) );
CREATE TABLE dsp_compliance ( publication_id TEXT NOT NULL REFERENCES weekly_scorecard_publications(id) ON DELETE CASCADE, row_index INTEGER NOT NULL, week TEXT, data_date TEXT, transporter_id TEXT, tracking_id TEXT, event_id TEXT, impact INTEGER, row TEXT NOT NULL CHECK(json_valid(row)), PRIMARY KEY(publication_id,row_index) );
CREATE TABLE dsp_feedback ( publication_id TEXT NOT NULL REFERENCES weekly_scorecard_publications(id) ON DELETE CASCADE, row_index INTEGER NOT NULL, week TEXT, data_date TEXT, transporter_id TEXT, tracking_id TEXT, event_id TEXT, impact INTEGER, row TEXT NOT NULL CHECK(json_valid(row)), PRIMARY KEY(publication_id,row_index) );
CREATE TABLE dsp_pickups ( publication_id TEXT NOT NULL REFERENCES weekly_scorecard_publications(id) ON DELETE CASCADE, row_index INTEGER NOT NULL, week TEXT, data_date TEXT, transporter_id TEXT, tracking_id TEXT, event_id TEXT, impact INTEGER, row TEXT NOT NULL CHECK(json_valid(row)), PRIMARY KEY(publication_id,row_index) );
CREATE TABLE dsp_quality ( publication_id TEXT NOT NULL REFERENCES weekly_scorecard_publications(id) ON DELETE CASCADE, row_index INTEGER NOT NULL, week TEXT, data_date TEXT, transporter_id TEXT, tracking_id TEXT, event_id TEXT, impact INTEGER, row TEXT NOT NULL CHECK(json_valid(row)), PRIMARY KEY(publication_id,row_index) );
CREATE TABLE dsp_safety ( publication_id TEXT NOT NULL REFERENCES weekly_scorecard_publications(id) ON DELETE CASCADE, row_index INTEGER NOT NULL, week TEXT, data_date TEXT, transporter_id TEXT, tracking_id TEXT, event_id TEXT, impact INTEGER, row TEXT NOT NULL CHECK(json_valid(row)), PRIMARY KEY(publication_id,row_index) );
CREATE TABLE dsp_team ( publication_id TEXT NOT NULL REFERENCES weekly_scorecard_publications(id) ON DELETE CASCADE, row_index INTEGER NOT NULL, week TEXT, data_date TEXT, transporter_id TEXT, tracking_id TEXT, event_id TEXT, impact INTEGER, row TEXT NOT NULL CHECK(json_valid(row)), PRIMARY KEY(publication_id,row_index) );
CREATE TABLE dsp_working_device ( publication_id TEXT NOT NULL REFERENCES weekly_scorecard_publications(id) ON DELETE CASCADE, row_index INTEGER NOT NULL, week TEXT, data_date TEXT, transporter_id TEXT, tracking_id TEXT, event_id TEXT, impact INTEGER, row TEXT NOT NULL CHECK(json_valid(row)), PRIMARY KEY(publication_id,row_index) );
CREATE TABLE owner_migrations (owner TEXT NOT NULL, id INTEGER NOT NULL, name TEXT NOT NULL, applied_at INTEGER NOT NULL, PRIMARY KEY(owner, id));
CREATE TABLE pickup_failures ( publication_id TEXT NOT NULL REFERENCES weekly_scorecard_publications(id) ON DELETE CASCADE, row_index INTEGER NOT NULL, week TEXT, data_date TEXT, transporter_id TEXT, tracking_id TEXT, event_id TEXT, impact INTEGER, row TEXT NOT NULL CHECK(json_valid(row)), PRIMARY KEY(publication_id,row_index) );
CREATE TABLE returns_to_station ( publication_id TEXT NOT NULL REFERENCES weekly_scorecard_publications(id) ON DELETE CASCADE, row_index INTEGER NOT NULL, week TEXT, data_date TEXT, transporter_id TEXT, tracking_id TEXT, event_id TEXT, impact INTEGER, row TEXT NOT NULL CHECK(json_valid(row)), PRIMARY KEY(publication_id,row_index) );
CREATE TABLE safety_events ( publication_id TEXT NOT NULL REFERENCES weekly_scorecard_publications(id) ON DELETE CASCADE, row_index INTEGER NOT NULL, week TEXT, data_date TEXT, transporter_id TEXT, tracking_id TEXT, event_id TEXT, impact INTEGER, row TEXT NOT NULL CHECK(json_valid(row)), PRIMARY KEY(publication_id,row_index) );
CREATE TABLE schema_migrations (id INTEGER PRIMARY KEY, name TEXT NOT NULL, applied_at INTEGER NOT NULL);
CREATE TABLE settings(key TEXT PRIMARY KEY,value TEXT NOT NULL CHECK(json_valid(value)));
CREATE TABLE storage_identity (dsp_id TEXT NOT NULL, provider TEXT NOT NULL, source TEXT NOT NULL);
CREATE TABLE weekly_scorecard_publications ( id TEXT PRIMARY KEY, job_id TEXT NOT NULL UNIQUE, week TEXT NOT NULL, station TEXT NOT NULL, company_id TEXT NOT NULL, dsp_code TEXT NOT NULL, started_at TEXT NOT NULL, collected_at TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 0 CHECK(active IN (0,1)), row_count INTEGER NOT NULL, adapter_version INTEGER NOT NULL , scope_verified INTEGER NOT NULL DEFAULT 0 CHECK(scope_verified IN (0,1)));
CREATE TABLE weekly_scorecard_schema (version INTEGER PRIMARY KEY CHECK(version=1));
CREATE TABLE weekly_scorecard_sources ( publication_id TEXT NOT NULL REFERENCES weekly_scorecard_publications(id) ON DELETE CASCADE, dataset TEXT NOT NULL, source TEXT NOT NULL CHECK(source IN ('api','csv')), url TEXT NOT NULL, row_count INTEGER NOT NULL, PRIMARY KEY(publication_id,dataset) );
CREATE TABLE weekly_scorecard_transition(version INTEGER PRIMARY KEY CHECK(version=1));
CREATE TABLE weekly_scorecard_weeks ( week TEXT NOT NULL, station TEXT NOT NULL, checked_at TEXT NOT NULL, posted INTEGER NOT NULL CHECK(posted IN (0,1)), publication_id TEXT REFERENCES weekly_scorecard_publications(id) ON DELETE SET NULL, scope_verified INTEGER NOT NULL DEFAULT 0 CHECK(scope_verified IN (0,1)), PRIMARY KEY(week,station) );
CREATE UNIQUE INDEX active_weekly_scorecard_week ON weekly_scorecard_publications(week,station,company_id) WHERE active=1;
CREATE INDEX customer_feedback_transporter ON customer_feedback(transporter_id);
CREATE INDEX delivery_concessions_transporter ON delivery_concessions(transporter_id);
CREATE INDEX driver_safety_transporter ON driver_safety(transporter_id);
CREATE INDEX driver_weekly_scorecards_transporter ON driver_weekly_scorecards(transporter_id);
CREATE INDEX dsp_compliance_transporter ON dsp_compliance(transporter_id);
CREATE INDEX dsp_feedback_transporter ON dsp_feedback(transporter_id);
CREATE INDEX dsp_pickups_transporter ON dsp_pickups(transporter_id);
CREATE INDEX dsp_quality_transporter ON dsp_quality(transporter_id);
CREATE INDEX dsp_safety_transporter ON dsp_safety(transporter_id);
CREATE INDEX dsp_team_transporter ON dsp_team(transporter_id);
CREATE INDEX dsp_working_device_transporter ON dsp_working_device(transporter_id);
CREATE INDEX pickup_failures_transporter ON pickup_failures(transporter_id);
CREATE INDEX returns_to_station_transporter ON returns_to_station(transporter_id);
CREATE INDEX safety_events_transporter ON safety_events(transporter_id);
CREATE INDEX weekly_scorecard_history ON weekly_scorecard_publications(week,collected_at DESC);
