CREATE TABLE account_passkeys ( id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, credential TEXT NOT NULL, name TEXT NOT NULL, created_at INTEGER NOT NULL );
CREATE TABLE agent_key_dsps ( key_id TEXT NOT NULL REFERENCES agent_keys(id) ON DELETE CASCADE, dsp_id TEXT NOT NULL REFERENCES dsps(id), PRIMARY KEY(key_id, dsp_id) );
CREATE TABLE agent_keys ( id TEXT PRIMARY KEY, name TEXT NOT NULL, hash TEXT NOT NULL UNIQUE, hint TEXT NOT NULL, user_id TEXT NOT NULL REFERENCES users(id), all_dsps INTEGER NOT NULL CHECK(all_dsps IN (0,1)), access TEXT NOT NULL CHECK(access IN ('read','operator')), tools TEXT NOT NULL CHECK(tools IN ('full','essential')), locations INTEGER NOT NULL CHECK(locations IN (0,1)), created_at TEXT NOT NULL, expires_at TEXT, revoked_at TEXT, last_used_at TEXT, last_client TEXT );
CREATE TABLE audit (id INTEGER PRIMARY KEY, at TEXT NOT NULL, actor_id TEXT REFERENCES users(id), dsp_id TEXT REFERENCES dsps(id), action TEXT NOT NULL, detail TEXT NOT NULL DEFAULT '', actor_name TEXT, data TEXT, shown INTEGER);
CREATE TABLE authenticator_apps ( user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, secret TEXT NOT NULL, created_at INTEGER NOT NULL, last_counter INTEGER NOT NULL DEFAULT -1 );
CREATE TABLE driver_codes ( code TEXT PRIMARY KEY, dsp_id TEXT NOT NULL, created_at TEXT NOT NULL );
CREATE TABLE dsp_features ( dsp_id TEXT NOT NULL REFERENCES dsps(id), feature TEXT NOT NULL, enabled INTEGER NOT NULL CHECK(enabled IN (0,1)), changed_by TEXT, changed_at TEXT NOT NULL, PRIMARY KEY(dsp_id,feature) );
CREATE TABLE dsps (id TEXT PRIMARY KEY, name TEXT NOT NULL, environment TEXT NOT NULL CHECK(environment IN ('production','preview')), status TEXT NOT NULL CHECK(status IN ('provisioning','active','suspended','failed')), timezone TEXT NOT NULL, permanent INTEGER NOT NULL DEFAULT 0 CHECK(permanent IN (0,1)), revision INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL);
CREATE TABLE invitations (hash TEXT PRIMARY KEY, dsp_id TEXT NOT NULL REFERENCES dsps(id), email TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('owner','manager','member')), expires_at INTEGER NOT NULL, created_by TEXT NOT NULL REFERENCES users(id), used_at INTEGER, role_id TEXT);
CREATE TABLE memberships (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), dsp_id TEXT NOT NULL REFERENCES dsps(id), role TEXT NOT NULL CHECK(role IN ('owner','manager','member')), role_id TEXT REFERENCES roles(id), UNIQUE(user_id,dsp_id));
CREATE TABLE outbox (id TEXT PRIMARY KEY, encrypted_message TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', attempts INTEGER NOT NULL DEFAULT 0, available_at INTEGER NOT NULL, sent_at TEXT, created_at INTEGER, last_attempt_at INTEGER, last_error TEXT, kind TEXT, invitation_hash TEXT, user_id TEXT);
CREATE TABLE passkeys ( id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, credential TEXT NOT NULL, name TEXT NOT NULL, created_at INTEGER NOT NULL );
CREATE TABLE recovery_codes ( hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE );
CREATE TABLE resets (hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), user_version INTEGER NOT NULL, expires_at INTEGER NOT NULL, used_at INTEGER);
CREATE TABLE roles (id TEXT PRIMARY KEY, dsp_id TEXT NOT NULL REFERENCES dsps(id), name TEXT NOT NULL COLLATE NOCASE, permissions TEXT NOT NULL DEFAULT '[]', system INTEGER NOT NULL DEFAULT 0 CHECK(system IN (0,1)), created_at TEXT NOT NULL, UNIQUE(dsp_id,name));
CREATE TABLE schema_migrations (id INTEGER PRIMARY KEY, name TEXT NOT NULL, applied_at INTEGER NOT NULL);
CREATE TABLE security_challenges ( session_hash TEXT PRIMARY KEY REFERENCES sessions(hash) ON DELETE CASCADE, kind TEXT NOT NULL, state TEXT NOT NULL, expires_at INTEGER NOT NULL );
CREATE TABLE session_metadata ( session_hash TEXT PRIMARY KEY REFERENCES sessions(hash) ON DELETE CASCADE, device TEXT NOT NULL );
CREATE TABLE session_security ( session_hash TEXT PRIMARY KEY REFERENCES sessions(hash) ON DELETE CASCADE, verified_at INTEGER NOT NULL DEFAULT 0, password_verified_at INTEGER NOT NULL DEFAULT 0 );
CREATE TABLE sessions (hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), user_version INTEGER NOT NULL, expires_at INTEGER NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE throttle (key TEXT PRIMARY KEY, count INTEGER NOT NULL, reset_at INTEGER NOT NULL, namespace TEXT NOT NULL DEFAULT 'legacy');
CREATE TABLE users (id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE COLLATE NOCASE, first_name TEXT NOT NULL, last_name TEXT NOT NULL, password TEXT NOT NULL, platform_owner INTEGER NOT NULL DEFAULT 0 CHECK(platform_owner IN (0,1)), status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','disabled')), version INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL);
CREATE INDEX account_passkeys_user ON account_passkeys(user_id);
CREATE INDEX audit_dsp_time ON audit(dsp_id,id DESC);
CREATE INDEX invitations_dsp_owner ON invitations(dsp_id,role,expires_at DESC) WHERE used_at IS NULL;
CREATE INDEX invitations_expiry ON invitations(expires_at);
CREATE INDEX invitations_role ON invitations(role_id) WHERE used_at IS NULL;
CREATE INDEX memberships_dsp_role ON memberships(dsp_id,role,user_id);
CREATE INDEX memberships_role ON memberships(role_id);
CREATE INDEX outbox_last_attempt ON outbox(last_attempt_at DESC);
CREATE INDEX outbox_pending ON outbox(status,available_at);
CREATE INDEX outbox_sent ON outbox(sent_at DESC);
CREATE INDEX passkeys_user ON passkeys(user_id);
CREATE UNIQUE INDEX permanent_dev ON dsps(permanent) WHERE permanent=1;
CREATE INDEX recovery_codes_user ON recovery_codes(user_id);
CREATE INDEX resets_expiry ON resets(expires_at);
CREATE UNIQUE INDEX roles_owner ON roles(dsp_id) WHERE system=1;
CREATE INDEX session_expiry ON sessions(expires_at);
CREATE INDEX throttle_expiry ON throttle(reset_at);
CREATE INDEX throttle_namespace_expiry ON throttle(namespace, reset_at);
